# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moving Photos' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Moving Photos
pod 'AFNetworking'
pod 'JPush'
pod 'ImagePicker-Objective-C'

end
